### ISSUE TITLE
MinTime and MaxTime? 

### ISSUE THREAD

**Issue by joeynylund** [NativeScript/nativescript-datetimepicker#24]
Anyway we could get these implemented? To customize to our business hours? Thanks

**Comment by tgpetrov** [comment]
@joeynylund 

Unfortunately this is not possible. The `nativescript-datetimepicker` plugin uses native widgets - [UIDatePicker](https://developer.apple.com/documentation/uikit/uidatepicker) for iOS and [TimePicker](https://developer.android.com/guide/topics/ui/controls/pickers) for Android and since neither of them provides such functionality it can not be exposed by this plugin too. 

You can subscribe to [timeChange](https://docs.nativescript.org/core-concepts/events#propertychange-event), verify the input and display some kind of warning if the time is not acceptable.

**Comment by patrikengborg** [comment]
I'm using the timeChange event and, in my case, if the end time precedes the start time I would like to cancel the change and revert it to the previous set time. But I can't seem to update the UI programatically. Is this possible? Please see my code sample below. Thanks.

```
onEndTimeChange({ value, oldValue }) {
  if (value <= this.startTime) {
    this.endTime = oldValue
    return false
  }

  this.endTime = value
}
```

**Comment by MCurran16** [comment]
You are able to do this with `nativescript-modal-datetimepicker` and they seem to be using the `UIDatePicker`. It also seems that you could potentially handle it somehow with android, although not sure the best way.

https://github.com/davecoffin/nativescript-modal-datetimepicker/blob/master/src/modal-datetimepicker.ios.ts#L279

https://github.com/davecoffin/nativescript-modal-datetimepicker/blob/master/src/modal-datetimepicker.android.ts#L104

@tgpetrov
