### ISSUE TITLE
[Feature Request] Improve UI

### ISSUE THREAD

**Issue by erkanarslan** [NativeScript/nativescript-datetimepicker#29]
This is a feature request. This plugin provides more native-looking date pickers: https://github.com/AntonioCuevaUrraco/nativescript-timedatepicker

However, it is not maintained at the moment and it has some build problems when you install it for the first time.

Maybe you can fork this plugin or use its components to improve nativescript-datetimepicker's UI.

**Comment by tgpetrov** [comment]
@erkanarslan 
Can you elaborate on "more native-looking"?
This plugin uses android and iOS native widgets - [Android DatePicker](https://developer.android.com/guide/topics/ui/controls/pickers) and [IOS UIDatePicker](https://developer.apple.com/documentation/uikit/uidatepicker). The Android widget has 2 modes - one with spinners (as used in this plugin) and one with calendar (as used in the other plugin) and while they are both 'native looking', we are using the one with spinners because it allows better customisation and more importantly - looks similar to the iOS version.

**Comment by erkanarslan** [comment]
The picker used in the other plugin looks better and the picker in this plugin looks like a web page popup. Maybe you can provide an option to choose which mode to use.

**Comment by tgpetrov** [comment]
The two plugins have conceptual differences, so combining them into a single plugin is not an option.

You can choose to use the one that suits your needs and preferences. Both are open-source so you can also contribute missing features and/or resolve issues. You can also fork either of them and apply whatever modifications you need.

Thank you for the provided feedback.

**Comment by erkanarslan** [comment]
I can contribute to solve some of the problems in the open source plugins but if I need to make changes on the native side, it is not possible for me since I don't have any android or ios development experience. I will continue to use other plugin in this case.
