### ISSUE TITLE
[Feature Request] A way to set the format of the date picker

### ISSUE THREAD

**Issue by mhtghn** [NativeScript/nativescript-datetimepicker#40]
Im currently working in a mobile app using NativeScript. And the user of the app can select a date and data will be displayed depending on the date selected. The user can also select which type of date he want to select (day, month or year).

It will be very helpful to have a way to set a format for the datepicker, for example to set a format of months and only the month and the year will be displayed. That way depending on the type of date the user selected, the app will display the correct format (not always dd/MM/YYYY as it works currently).

**Comment by tgpetrov** [comment]
Hello @mhtghn 

Unfortunately this is not possible. The `nativescript-datetimepicker` plugin uses native widgets - [UIDatePicker](https://developer.apple.com/documentation/uikit/uidatepicker) for iOS and [DatePicker](https://developer.android.com/guide/topics/ui/controls/pickers) for Android and since neither of them provides such functionality it can not be exposed by this plugin too. 

In the case where you need to select only year and month, you will have to use another way of selection, for example add 2 ListPicker-s, and then manually generate a date based on their input.
