### ISSUE TITLE
Datepicker title of the lists

### ISSUE THREAD

**Issue by Izrab** [NativeScript/nativescript-datetimepicker#8]
I want to write the title of the datepicker month, year, and day lists, like this
![captuhre](https://user-images.githubusercontent.com/22328131/53958359-b1467400-4095-11e9-8abf-9b6d5262d593.PNG)

But, I should be able to write the titles in Arabic too, beside English.

**Comment by tgpetrov** [comment]
Hello @Izrab 
Unfortunately this is not possible. The `nativescript-datetimepicker` plugin uses native widgets - [UIDatePicker](https://developer.apple.com/documentation/uikit/uidatepicker) for iOS and [DatePicker](https://developer.android.com/guide/topics/ui/controls/pickers) for Android and since neither of them provides such functionality it can not be exposed by this plugin too.
