### ISSUE TITLE
Datepicker numerical month list 

### ISSUE THREAD

**Issue by Izrab** [NativeScript/nativescript-datetimepicker#9]
I want to select the month as numbers, like day and year, Instead of month names (e.g. "Jan", "Feb", etc), rather 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12.
![captuhre](https://user-images.githubusercontent.com/22328131/53961002-77c53700-409c-11e9-9acc-7371cc867320.PNG)

**Comment by tgpetrov** [comment]
Hello @Izrab 

Unfortunately this is not possible. The `nativescript-datetimepicker` plugin uses native widgets - [UIDatePicker](https://developer.apple.com/documentation/uikit/uidatepicker) for iOS and [DatePicker](https://developer.android.com/guide/topics/ui/controls/pickers) for Android and since neither of them provides such functionality it can not be exposed by this plugin too. 

You can change whether the month is displayed as text or as number in the text field after date is selected through the `dateFormat` property (for example format dd-MM-yyyy will display numbers, while dd-MMMM-yyyy will display month names), however the picker itself will always display month names.
